name: rl_matrix
version: 0.5.0
author: R.S. Schermer <roland0507@gmail.com>
description: Provides an immutable implementation for matrices of real numbers in Dart, based on Java's JAMA package.
homepage: https://github.com/RSSchermer/rl_matrix
documentation:
dependencies:
  collection: '>=1.1.1 <2.0.0'
  quiver: '>=0.21.0 <0.22.0'
dev_dependencies:
  path: '>=1.0.0 <2.0.0'
  test: '>=0.10.0'
