name: rl_matrix
version: 0.6.4
author: R.S. Schermer <roland0507@gmail.com>
description: Provides an immutable implementation for matrices of real numbers in Dart, based on Java's JAMA package.
homepage: https://github.com/RSSchermer/rl_matrix
documentation:
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  collection: '^1.14.0'
  quiver: '^0.25.0'
dev_dependencies:
  path: '^1.4.0'
  test: '^0.12.0'
